/* Browser replacements for the Android bridges used by the shared game UI.
 * Original works stay in the player's IndexedDB; only a selected save is cloud-synced. */
(function(){
  if (window.NativeWorldSource) return;
  var STORE='cute-disciple-canon', KEY='sources', memory={}, dbPromise=null;
  function safe(v){try{return JSON.parse(JSON.stringify(v));}catch(_e){return null;}}
  function id(){return 'canon_'+Date.now()+'_'+Math.random().toString(36).slice(2,9);}
  function openDb(){
    if(dbPromise)return dbPromise;
    dbPromise=new Promise(function(resolve,reject){
      var req=indexedDB.open(STORE,1);
      req.onupgradeneeded=function(){if(!req.result.objectStoreNames.contains(KEY))req.result.createObjectStore(KEY,{keyPath:'id'});};
      req.onsuccess=function(){resolve(req.result);};req.onerror=function(){reject(req.error);};
    });
    return dbPromise;
  }
  function persist(source){return openDb().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction(KEY,'readwrite');tx.objectStore(KEY).put(safe(source));tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});}).catch(function(){});}
  function remove(id){return openDb().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction(KEY,'readwrite');tx.objectStore(KEY).delete(id);tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error);};});}).catch(function(){});}
  function loadAll(){return openDb().then(function(db){return new Promise(function(resolve,reject){var req=db.transaction(KEY,'readonly').objectStore(KEY).getAll();req.onsuccess=function(){(req.result||[]).forEach(function(s){if(s&&s.id)memory[s.id]=s;});resolve();};req.onerror=function(){reject(req.error);};});}).then(function(){if(window.onNativeCanonLibraryEvent)window.onNativeCanonLibraryEvent(true,'原著库已加载');}).catch(function(){});}
  function rows(){return Object.keys(memory).map(function(k){return memory[k];});}
  function summary(s){return {id:s.id,name:s.name,type:s.type,encoding:s.encoding||'UTF-8',chars:s.chars||0,chunks:(s.chunks||[]).length,createdAt:s.createdAt||0};}
  function download(name,content){var blob=new Blob([content],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){a.remove();URL.revokeObjectURL(url);},120);}
  function choose(accept,done){var input=document.createElement('input');input.type='file';input.accept=accept;input.onchange=function(){var f=input.files&&input.files[0];if(f)done(f);};input.click();}
  function readText(file){return file.arrayBuffer().then(function(buf){var utf8=new TextDecoder('utf-8').decode(buf),bad=(utf8.match(/\uFFFD/g)||[]).length;if(bad>Math.max(8,utf8.length/120)){try{return new TextDecoder('gb18030').decode(buf);}catch(_e){}}return utf8;});}
  function loadScript(src,global){return new Promise(function(resolve,reject){if(global&&window[global])return resolve(window[global]);var s=document.createElement('script');s.src=src;s.onload=function(){resolve(global?window[global]:true);};s.onerror=function(){reject(new Error('加载解析组件失败'));};document.head.appendChild(s);});}
  function extractEpub(file){return file.arrayBuffer().then(function(buf){return loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js','JSZip').then(function(){return window.JSZip.loadAsync(buf);}).then(function(zip){var names=Object.keys(zip.files).filter(function(n){return /\.(x?html?|htm)$/i.test(n)&&!/nav\./i.test(n);}).sort();return Promise.all(names.map(function(n){return zip.files[n].async('text').then(function(html){return new DOMParser().parseFromString(html,'text/html').body.textContent||'';});})).then(function(parts){return parts.join('\n\n');});});});}
  function extractDocx(file){return file.arrayBuffer().then(function(buf){return loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.10.0/mammoth.browser.min.js','mammoth').then(function(){return window.mammoth.extractRawText({arrayBuffer:buf}).then(function(r){return r.value||'';});});});}
  function extractPdf(file){return file.arrayBuffer().then(function(buf){return loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib').then(function(){window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';return window.pdfjsLib.getDocument({data:buf}).promise;}).then(function(pdf){var chain=Promise.resolve([]);for(var n=1;n<=pdf.numPages;n++)(function(pageNo){chain=chain.then(function(parts){return pdf.getPage(pageNo).then(function(page){return page.getTextContent().then(function(c){parts.push(c.items.map(function(i){return i.str;}).join(''));return parts;});});});})(n);return chain.then(function(parts){return parts.join('\n\n');});});});}
  function extract(file){var ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='epub')return extractEpub(file);if(ext==='docx')return extractDocx(file);if(ext==='pdf')return extractPdf(file);if(ext==='json')return readText(file).then(function(t){try{return JSON.stringify(JSON.parse(t),null,2);}catch(_e){return t;}});if(ext==='fb2')return readText(file).then(function(t){return new DOMParser().parseFromString(t,'application/xml').documentElement.textContent||t;});if(ext==='mobi'||ext==='azw'||ext==='azw3')return Promise.reject(new Error('浏览器版暂不能安全解码 MOBI/AZW；请先转换为 EPUB、TXT 或 DOCX 后导入。'));return readText(file);}
  function makeSource(name,type,text){text=String(text||'').replace(/\u0000/g,'').trim();if(!text)throw new Error('未从文件中提取到可用文字');var size=6000,chunks=[];for(var at=0;at<text.length;at+=size)chunks.push({ordinal:chunks.length,text:text.slice(at,at+size),facts:[]});var s={id:id(),name:name||'未命名原著',type:type||'文本',encoding:'UTF-8',chars:text.length,chunks:chunks,createdAt:Date.now()};memory[s.id]=s;persist(s);return s;}
  function score(text,q){q=String(q||'').toLowerCase();if(!q)return 0;var x=String(text||'').toLowerCase(),n=0,p=-1;while((p=x.indexOf(q,p+1))>=0)n++;return n;}
  function passages(source,q,limit){var list=(source&&source.chunks||[]).map(function(c){return {chapter:(c.ordinal||0)+1,offset:(c.ordinal||0)*6000,text:c.text,score:score(c.text,q)};}).filter(function(x){return !q||x.score>0;});if(!list.length&&source&&source.chunks&&source.chunks.length)list=[{chapter:1,offset:0,text:source.chunks[0].text,score:0}];return list.sort(function(a,b){return b.score-a.score;}).slice(0,limit||3);}
  function findSource(sid){return memory[String(sid)]||null;}
  window.NativeWorldSource={
    importWorldFile:function(){choose('.txt,.md,.markdown,.json,.docx,.pdf,.epub,.fb2,.mobi,.azw,.azw3,text/plain,application/json,application/pdf,application/epub+zip',function(file){if(window.onNativeWorldSourceImportProgress)window.onNativeWorldSourceImportProgress('正在读取 '+file.name+'…');extract(file).then(function(text){var source=makeSource(file.name,file.name.split('.').pop().toUpperCase(),text);if(window.onNativeWorldSourceImported)window.onNativeWorldSourceImported({name:source.name,type:source.type,encoding:source.encoding,sessionId:source.id,canonSourceId:source.id,canonChunks:source.chunks.length,chars:source.chars},text.slice(0,12000));}).catch(function(e){if(window.onNativeWorldSourceImportError)window.onNativeWorldSourceImportError(e.message||String(e));});});},
    readWorldChunk:function(sessionId,offset,limit){var s=findSource(sessionId),at=Math.max(0,parseInt(offset,10)||0),need=Math.max(1,parseInt(limit,10)||6000),start=Math.floor(at/6000),skip=at%6000,text='';if(s){for(var i=start;i<s.chunks.length&&text.length<need;i++){var part=s.chunks[i].text||'';if(i===start)part=part.slice(skip);text+=part;}}setTimeout(function(){if(window.onNativeWorldSourceChunk)window.onNativeWorldSourceChunk(sessionId,at,text.slice(0,need),!s||at+need>=(s.chars||0));},0);},
    listCanonSources:function(){return JSON.stringify(rows().map(summary));},
    previewCanonSource:function(sid,limit){var s=findSource(sid);return JSON.stringify(s?{available:true,id:s.id,name:s.name,type:s.type,encoding:s.encoding,chars:s.chars,chunks:s.chunks.length,preview:s.chunks.map(function(c){return c.text;}).join('\n').slice(0,limit||12000)}:{available:false,error:'原著不存在'});},
    readCanonChunk:function(sid,ordinal){var s=findSource(sid),c=s&&s.chunks[parseInt(ordinal,10)];return JSON.stringify(c?{available:true,ordinal:c.ordinal,text:c.text}:{available:false});},
    replaceCanonFacts:function(sid,ordinal,raw){var s=findSource(sid),c=s&&s.chunks[parseInt(ordinal,10)];if(!c)return 0;try{c.facts=JSON.parse(raw)||[];}catch(_e){c.facts=[];}persist(s);return c.facts.length;},
    searchCanon:function(sid,q,limit){var s=findSource(sid);return JSON.stringify({passages:passages(s,q,limit||3)});},
    searchCanonFacts:function(sid,q,limit){var s=findSource(sid),out=[];if(s)(s.chunks||[]).forEach(function(c){(c.facts||[]).forEach(function(f){if(!q||score((f.label||'')+' '+(f.detail||''),q))out.push({chunk:c.ordinal,kind:f.kind,label:f.label,detail:f.detail});});});return JSON.stringify({facts:out.slice(0,limit||8)});},
    searchCanonContext:function(requestId,sid,q,limit,cursor){var s=findSource(sid),ps=passages(s,q,limit||6),next=ps.length?Math.max(0,(ps[0].chapter||1)-1):Math.max(0,parseInt(cursor,10)||0);setTimeout(function(){if(window.onNativeCanonContext)window.onNativeCanonContext(requestId,JSON.stringify({available:!!s,cursor:next,passages:ps,facts:[]}));},0);},
    searchCanonLibrary:function(q,limit){var out=[];rows().forEach(function(s){passages(s,q,limit||12).forEach(function(p){if(p.score>0)out.push({sourceId:s.id,name:s.name,chunk:p.chapter-1,text:p.text});});});return JSON.stringify({results:out.slice(0,limit||12)});},
    deleteCanonSource:function(sid){delete memory[String(sid)];remove(String(sid));if(window.onNativeCanonLibraryEvent)window.onNativeCanonLibraryEvent(true,'原著已删除');},
    exportCanonSource:function(sid,name){var s=findSource(sid);if(!s)throw new Error('原著不存在');download((name||s.name||'canon')+'.json',JSON.stringify({format:'cute-disciple-canon-web',version:1,source:s},null,2));},
    importCanonPackage:function(){choose('.json,application/json',function(file){readText(file).then(function(t){var p=JSON.parse(t),s=p.source||p;if(!s||!Array.isArray(s.chunks))throw new Error('不是可识别的原著包');s.id=id();memory[s.id]=s;persist(s);if(window.onNativeCanonLibraryEvent)window.onNativeCanonLibraryEvent(true,'原著包已导入');}).catch(function(e){if(window.onNativeCanonLibraryEvent)window.onNativeCanonLibraryEvent(false,e.message||String(e));});});}
  };
  loadAll();
})();
