CREATE TABLE IF NOT EXISTS save (id INTEGER PRIMARY KEY, version INTEGER DEFAULT 3, state TEXT NOT NULL, updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS snapshots (id INTEGER PRIMARY KEY, mid INTEGER NOT NULL, data TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS worlds (id TEXT PRIMARY KEY, name TEXT NOT NULL DEFAULT '徒界', tone TEXT DEFAULT '', era TEXT DEFAULT '入门元年', data TEXT DEFAULT '{}');
CREATE TABLE IF NOT EXISTS disciples (id TEXT PRIMARY KEY, world_id TEXT REFERENCES worlds(id), name TEXT DEFAULT '', age TEXT DEFAULT '', sex TEXT DEFAULT '', data TEXT DEFAULT '{}');
CREATE TABLE IF NOT EXISTS npcs (id INTEGER PRIMARY KEY AUTOINCREMENT, disciple_id TEXT REFERENCES disciples(id), name TEXT NOT NULL, relation TEXT DEFAULT '', dynamic TEXT DEFAULT '', personality TEXT DEFAULT '', memories TEXT DEFAULT '[]', knowledge TEXT DEFAULT '[]', first_seen INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, type TEXT DEFAULT '日常', description TEXT DEFAULT '', price REAL DEFAULT 0, coin_price INTEGER DEFAULT 0, tier INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, from_who TEXT NOT NULL, content TEXT DEFAULT '', msg_type TEXT DEFAULT 'npc', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS news (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, summary TEXT DEFAULT '', date TEXT DEFAULT '', content TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS chat_history (id INTEGER PRIMARY KEY AUTOINCREMENT, disciple_id TEXT REFERENCES disciples(id), role TEXT NOT NULL CHECK(role IN ('user','assistant','system')), content TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
